spring:
  profiles:
    active: local

---
spring:
  profiles: local
  datasource:
    data: classpath:data-h2.sql
    sql-script-encoding: UTF-8
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  h2:
    console:
      enabled: true